set echo on
set timing on
spool count.log
select 'EDW_ASI.GCP_FIBER_RANGE',count(1) from EDW_ASI.GCP_FIBER_RANGE;
select 'EDW_ASI.GCP_HIER_CIRCUIT_NEW',count(1) from EDW_ASI.GCP_HIER_CIRCUIT_NEW;
select 'EDW_ASI.GCP_HIER_SCID_CXR',count(1) from EDW_ASI.GCP_HIER_SCID_CXR;
select 'EDW_ASI.GCP_HIER_EQUIP',count(1) from EDW_ASI.GCP_HIER_EQUIP;
select 'EDW_ASI.GCP_HIER_ALL_CKT',count(1) from EDW_ASI.GCP_HIER_ALL_CKT;
select 'EDW_ASI.GCP_HIER_EQUIP_CKTID',count(1) from EDW_ASI.GCP_HIER_EQUIP_CKTID;
select 'EDW_ASI.GCP_EQ_SCID',count(1) from EDW_ASI.GCP_EQ_SCID;
select 'EDW_ASI.GCP_HECI',count(1) from EDW_ASI.GCP_HECI;
select 'EDW_ASI.GCP_HIER_SONET_INTER_TMP',count(1) from EDW_ASI.GCP_HIER_SONET_INTER_TMP;
select 'EDW_ASI.GCP_HIER_SONET_INTER',count(1) from EDW_ASI.GCP_HIER_SONET_INTER;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP01',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP01;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP02',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP02;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP03',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP03;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP04',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP04;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP05',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP05;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP06',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP06;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP07',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP07;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP08',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP08;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP09',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP09;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP10',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP10;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP11',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP11;
select 'EDW_ASI.GCP_HIER_ALL_CXR_TMP12',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_TMP12;
select 'EDW_ASI.GCP_HIER_ALL_CXR',count(1) from EDW_ASI.GCP_HIER_ALL_CXR;
select 'EDW_ASI.GCP_HIER_ALL_CXR_IE_ADD',count(1) from EDW_ASI.GCP_HIER_ALL_CXR_IE_ADD;
select 'EDW_ASI.GCP_HIER_CIRCUIT_HIER',count(1) from EDW_ASI.GCP_HIER_CIRCUIT_HIER;
select 'EDW_ASI.GCP_HIER_SKIP_LEVEL',count(1) from EDW_ASI.GCP_HIER_SKIP_LEVEL;
select 'EDW_ASI.GCP_CXR_WITH_SUBSCID',count(1) from EDW_ASI.GCP_CXR_WITH_SUBSCID;
select 'EDW_ASI.GCP_SCID_SUBSCID',count(1) from EDW_ASI.GCP_SCID_SUBSCID;
select 'EDW_ASI.GCP_FIBER_HI_LEVEL',count(1) from EDW_ASI.GCP_FIBER_HI_LEVEL;
select 'EDW_ASI.GCP_FIBER_SUMMARY',count(1) from EDW_ASI.GCP_FIBER_SUMMARY;
select 'EDW_ASI.GCP_FIBER_STRAND',count(1) from EDW_ASI.GCP_FIBER_STRAND;
select 'EDW_ASI.GCP_GRANITE_FIBER_VIEW',count(1) from EDW_ASI.GCP_GRANITE_FIBER_VIEW;
select 'EDW_ASI.GCP_TIRKS_CKT_TMP01',count(1) from EDW_ASI.GCP_TIRKS_CKT_TMP01;
select 'EDW_ASI.GCP_NUMTWELVE_TWO_CLLI',count(1) from EDW_ASI.GCP_NUMTWELVE_TWO_CLLI;
select 'EDW_ASI.GCP_NUMTWELVE_SCID',count(1) from EDW_ASI.GCP_NUMTWELVE_SCID;
select 'EDW_ASI.GCP_FOLDED_RING',count(1) from EDW_ASI.GCP_FOLDED_RING;
select 'EDW_ASI.GCP_HIER_PREPMCO',count(1) from EDW_ASI.GCP_HIER_PREPMCO;
select 'EDW_ASI.GCP_MCO_AGID',count(1) from EDW_ASI.GCP_MCO_AGID;
select 'EDW_ASI.GCP_FIBERRANGE_VIEW',count(1) from EDW_ASI.GCP_FIBERRANGE_VIEW;
select 'EDW_ASI.GCP_FIBER_SUMMARY_VIEW',count(1) from EDW_ASI.GCP_FIBER_SUMMARY_VIEW;
select 'EDW_ASI.GCP_FIBER4GRANITE_TIRKS_VIEW',count(1) from EDW_ASI.GCP_FIBER4GRANITE_TIRKS_VIEW;
spo off